services:
  # https://docs.linuxserver.io/images/docker-transmission/
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
      # - WHITELIST=127.0.0.1,::1,100.105.211.56
      - PEERPORT=51413
    volumes:
      - ./transmission:/config
      - /data:/downloads 
      - /data/downloads/torrents:/watch
      - /mnt/hdd:/hdd
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # https://jellyfin.org/docs/general/installation/container/
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: /data/movies
        target: /movies
      - type: bind
        source: /data/shows
        target: /shows
        read_only: true
      - type: bind
        source: /mnt/hdd
        target: /hdd       
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # https://hub.docker.com/r/linuxserver/plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - device=/dev/dri:/dev/dri
    volumes:
      - ./plex/library:/config
      - /data/shows:/tv
      - /data/movies:/movies
      - /data/videos:/videos
      - /mnt/hdd:/hdd
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./navidrome:/data"
      - "/data/music:/music:ro"

#  cloudflared:
#    image: cloudflare/cloudflared:latest
#    container_name: cloudflared
#    restart: unless-stopped
#    command: tunnel run
#    environment:
#      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
