services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /data/ollama:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 8081:8080/tcp
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    volumes:
      - /data/open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
