name: transmission

services:
    # https://docs.linuxserver.io/images/docker-transmission/
    transmission:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - USER=${TRANSMISSION_USERNAME}
            - PASS=${TRANSMISSION_PASSWORD}
            # - WHITELIST=127.0.0.1,::1,100.105.211.56
            - PEERPORT=51413
        volumes:
            - ./transmission:/config
            - /data:/downloads
            - /data/downloads/torrents:/watch
            - /mnt/hdd:/hdd
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
