FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    poppler-utils libjpeg62-turbo zlib1g libpq5 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir flask gunicorn requests python-docx python-pptx \
    pillow google-genai pdf2image thefuzz holidays

COPY app.py /app/app.py

WORKDIR /app

CMD ["gunicorn","-b","0.0.0.0:8000","--timeout","600","--workers","2","app:app"]