- name: Home
  hide-desktop-navigation: false
  columns:
    - size: small
      widgets:

        - type: calendar
          first-day-of-week: monday

        - type: server-stats
          servers:
            - type: local
              name: Ubuntu           

        - $include: speedtest-tracker.yml

        - type: dns-stats
          service: adguard
          url: http://${HOST_TS_IP}/
          username: ${ADGUARD_USERNAME}
          password: ${ADGUARD_PASSWORD}

        - type: bookmarks
          groups:
            - title: Admin
              color: 10 70 50
              links: 
              - title: Tailscale Admin Console
                url: https://console.tailscale.com/admin/machines
              - title: GitHub - abdullahau
                url: https://github.com/abdullahau
              - title: Raindrop.io
                url: https://app.raindrop.io
            - title: News
              color: 200 50 50
              links:
              - title: AllToc
                url: https://alltoc.com/
              - title: Biztoc
                url: https://biztoc.com/
              - title: Google News
                url: https://news.google.com/home?hl=en-US&gl=US&ceid=US:en
              - title: Financial Times
                url: https://www.ft.com/

    - size: full
      widgets:

        - type: docker-containers
          containers:
            glance:
              name: Glance
              description: Dashboard
              url: http://ubuntu:8080/
              icon: sh:glance
              hide: false
            jellyfin:
              name: Jellyfin
              description: Multimedia server
              url: http://ubuntu:8096/web/#/home
              icon: sh:jellyfin
              hide: false
            plex:
              name: Plex
              description: Multimedia server
              url: http://ubuntu:32400/web/index.html#!/
              icon: sh:plex
              hide: false
            transmission:
              name: Transmission
              description: BitTorrent client
              url: http://ubuntu:9091/transmission/web/
              icon: sh:transmission
              hide: false
            navidrome:
              name: Navidrome
              description: Music player
              url: http://ubuntu:4533/#/
              icon: sh:navidrome
              hide: false
            adguardhome:
              name: AdGuard Home
              description: Ads & trackers blocking
              url: http://ubuntu/
              icon: sh:adguard-home
              hide: false
            speedtest-tracker:
              name: Speedtest Tracker
              description: Track internet speed
              url: http://ubuntu:9080/admin
              icon: sh:speedtest-tracker
              hide: false
            motioneye:
              name: MotionEye
              description: NVR System
              url: http://ubuntu:8765/
              icon: sh:motioneye
              hide: false
            nodecast-tv:
              name: NodeCastTV
              description: IPTV Player
              url: http://ubuntu:3000/
              icon: sh:nodecast-tv
              hide: false
            open-webui:
              name: Open WebUI
              description: AI Interface
              url: http://ubuntu:8081
              icon: sh:open-webui
              hide: false
            ollama:
              name: Ollama
              description: Manage LLMs
              url: http://ubuntu:11434
              icon: sh:ollama
              hide: false

        - type: rss
          limit: 70
          collapse-after: 5
          style: vertical-list
          cache: 5d
          feeds:
            - url: https://www.bloomberg.com/authors/ARbTQlRLRjE/matthew-s-levine.rss
              title: Money Stuff - Matt Levine
            - url: https://aswathdamodaran.blogspot.com/feeds/posts/default
              title: Musings on Markets - Aswath Damodaran
            - url: https://adamtooze.substack.com/feed
              title: Chartbook - Adam Tooze
            - url: https://www.ft.com/alphaville?format=rss
              title: FT Alphaville
            - url: https://www.thedailyupside.com/feed/
              title: The Daily Upside
            - url: https://stratechery.com/feed/
              title: Stratechery - Ben Thompson
            - url: https://www.ben-evans.com/benedictevans/?format=rss
              title: Benedict Evans
            - url: http://ben-evans.com/rss
              title: Benedict Evans
            - url: https://rss.politico.com/morningmoney.xml
              title: Politico - Morning Money
            - url: https://www.thediff.co/rss/
              title: The Diff - Byrne Hobart
            - url: https://rss.beehiiv.com/feeds/uuk5kg8PFC.xml
              title: Short Squeez
            - url: https://rss.nytimes.com/services/xml/rss/nyt/Dealbook.xml
              title: DealBook
            - url: https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml
              title: NYT Economy

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCIALMKvObZNtJ6AmdCLP7Lg # Bloomberg Television
            - UCoUxsWakJucWg46KW5RsvPw # Financial Times
            - UCK7tptUDHh-RYDsdxO1-5QQ # The Wall Street Journal
            - UCASM0cgfkJxQ1ICmRilfHLw # Patrick Boyle
            - UCsBjURrPoezykLs9EqgamOA # Fireship

        - type: group
          widgets:
            - type: reddit
              subreddit: worldnews
              show-thumbnails: true
            - type: reddit
              subreddit: news
              show-thumbnails: true
            - type: reddit
              subreddit: economics
              show-thumbnails: true
            - type: reddit
              subreddit: finance
              show-thumbnails: true
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:

        - type: weather
          location: Dubai, United Arab Emirates
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"

        - type: markets
          markets:
            - symbol: VOO
              name: S&P 500
            - symbol: XLK
              name: S&P 500 Tech
            - symbol: VOOG
              name: S&P 500 Growth
            - symbol: VGK
              name: FTSE Europe ETF

        - type: repository
          repository: abdullahau/homelab

        - type: repository
          repository: abdullahau/dotfiles
