- name: Home
  hide-desktop-navigation: false
  columns:
    - size: small
      widgets:

        - type: calendar
          first-day-of-week: monday

        - type: server-stats
          servers:
            - type: local
              name: Ubuntu           

        - type: dns-stats
          service: adguard
          url: http://${HOST_TS_IP}/
          username: ${ADGUARD_USERNAME}
          password: ${ADGUARD_PASSWORD}

        - type: bookmarks
          groups:
            - title: Admin
              color: 10 70 50
              links: 
              - title: Tailscale Admin Console
                url: https://login.tailscale.com/admin/machines
              - title: GitHub - abdullahau
                url: https://github.com/abdullahau
            - title: News
              color: 200 50 50
              links:
              - title: Biztoc
                url: https://biztoc.com/
              - title: Google News
                url: https://news.google.com/home?hl=en-US&gl=US&ceid=US:en
              - title: Financial Times
                url: https://www.ft.com/

    - size: full
      widgets:

        - type: docker-containers
          containers:
            glance:
              name: Glance
              description: Dashboard
              url: http://ubuntu:8080/
              icon: sh:glance
              hide: false
            jellyfin:
              name: Jellyfin
              description: Multimedia server
              url: http://ubuntu:8096/web/#/home
              icon: sh:jellyfin
              hide: false
            plex:
              name: Plex
              description: Multimedia server
              url: http://ubuntu:32400/web/index.html#!/
              icon: sh:plex
              hide: false
            transmission:
              name: Transmission
              description: BitTorrent client
              url: http://ubuntu:9091/transmission/web/
              icon: sh:transmission
              hide: false
            swingmusic:
              name: Swing Music
              description: Music player
              url: http://ubuntu:1970/#/
              icon: sh:swing-music
              hide: false
            adguardhome:
              name: AdGuard Home
              description: Ads & trackers blocking
              url: http://ubuntu/
              icon: sh:adguard-home
              hide: false
            speedtest-tracker:
              name: Speedtest Tracker
              description: Track internet speed
              url: http://ubuntu:9080/admin
              icon: sh:speedtest-tracker
              hide: false
      
        - type: rss
          limit: 50
          collapse-after: 5
          style: vertical-list
          cache: 2d
          feeds:
            - url: https://www.bloomberg.com/authors/ARbTQlRLRjE/matthew-s-levine.rss
              title: Money Stuff - Matt Levine
            - url: https://aswathdamodaran.blogspot.com/feeds/posts/default
              title: Musings on Markets - Aswath Damodaran
            - url: https://adamtooze.substack.com/feed
              title: Chartbook - Adam Tooze
            - url: https://www.ft.com/alphaville?format=rss
              title: FT Alphaville

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCIALMKvObZNtJ6AmdCLP7Lg # Bloomberg Television
            - UCoUxsWakJucWg46KW5RsvPw # Financial Times
            - UCK7tptUDHh-RYDsdxO1-5QQ # The Wall Street Journal
            - UCASM0cgfkJxQ1ICmRilfHLw # Patrick Boyle
            - UCsBjURrPoezykLs9EqgamOA # Fireship

        - type: group
          widgets:
            - type: reddit
              subreddit: worldnews
              show-thumbnails: true
            - type: reddit
              subreddit: news
              show-thumbnails: true
            - type: reddit
              subreddit: economics
              show-thumbnails: true
            - type: reddit
              subreddit: finance
              show-thumbnails: true
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:

        - type: weather
          location: Dubai, United Arab Emirates
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"

        - type: markets
          markets:
            - symbol: VOO
              name: S&P 500
            - symbol: XLK
              name: S&P 500 Tech
            - symbol: VOOG
              name: S&P 500 Growth
            - symbol: VGK
              name: FTSE Europe ETF

        - type: repository
          repository: abdullahau/homelab

        - type: repository
          repository: abdullahau/dotfiles
